import { useMemo, useState } from "react";
import type { EChartsCoreOption } from "echarts/core";
import { aggregateBy, monthlySeries, temporalMatrix } from "../analytics/aggregations";
import { useFilters } from "../state/FilterContext";
import type { Fact, FilterKey } from "../types/dashboard";
import { EChart } from "./EChart";
const number = new Intl.NumberFormat("pt-BR");
const percent = new Intl.NumberFormat("pt-BR", { style: "percent", maximumFractionDigits: 1 });
const palette = ["#003770", "#2e72e0", "#20aaee", "#ffd500", "#068e3a", "#6f42c1"];
const heatmapGroups: Array<{ key: FilterKey; label: string; render?: (fact: Fact) => string }> = [{ key: "unitType", label: "Tipo de unidade" }, { key: "unitSummary", label: "Unidade" }, { key: "council", label: "Conselho" }, { key: "city", label: "Cidade" }, { key: "formId", label: "Formulário", render: (fact) => fact.formName }, { key: "responsibleName", label: "Responsável" }];
export function AnalyticsPanel() {
  const { filteredFacts, drillTo } = useFilters(); const [mode, setMode] = useState<"quantity" | "share">("quantity");
  const [heatmapGroup, setHeatmapGroup] = useState(heatmapGroups[0]);
  const total = filteredFacts.reduce((sum, fact) => sum + fact.quantity, 0);
  const forms = useMemo(() => aggregateBy(filteredFacts, "formId", (fact) => fact.formName), [filteredFacts]);
  const states = useMemo(() => aggregateBy(filteredFacts, "state"), [filteredFacts]); const months = useMemo(() => monthlySeries(filteredFacts), [filteredFacts]);
  const distinct = (key: keyof (typeof filteredFacts)[number]) => new Set(filteredFacts.map((fact) => fact[key]).filter(Boolean)).size;
  const valueOf = (item: { quantity: number; share: number }) => mode === "quantity" ? item.quantity : Number((item.share * 100).toFixed(2));
  const valueLabel = (value: number) => mode === "quantity" ? number.format(value) : `${value.toLocaleString("pt-BR")}%`;
  const timeline: EChartsCoreOption = { color: palette, tooltip: { trigger: "axis", valueFormatter: valueLabel }, grid: { left: 52, right: 24, top: 25, bottom: 58 }, xAxis: { type: "category", data: months.map((item) => item.key) }, yAxis: { type: "value" }, dataZoom: [{ type: "inside" }, { type: "slider", height: 18 }], series: [{ type: "line", smooth: true, symbolSize: 9, areaStyle: { opacity: .12 }, data: months.map(valueOf) }] };
  const formBars: EChartsCoreOption = { color: palette, tooltip: { trigger: "axis", valueFormatter: valueLabel }, grid: { left: 150, right: 30, top: 12, bottom: 32 }, xAxis: { type: "value", max: mode === "share" ? 100 : undefined }, yAxis: { type: "category", inverse: true, data: forms.slice(0, 10).map((item) => item.label) }, series: [{ type: "bar", data: forms.slice(0, 10).map(valueOf), itemStyle: { borderRadius: [0, 7, 7, 0] } }] };
  const treemap: EChartsCoreOption = { color: palette, tooltip: {}, series: [{ type: "treemap", roam: false, breadcrumb: { show: false }, label: { formatter: "{b}" }, data: forms.map((item) => ({ name: item.label, value: valueOf(item) })) }] };
  const stateBars: EChartsCoreOption = { color: ["#20aaee"], tooltip: { trigger: "axis", valueFormatter: valueLabel }, grid: { left: 42, right: 18, top: 12, bottom: 50 }, xAxis: { type: "category", data: states.map((item) => item.key), axisLabel: { rotate: 45 } }, yAxis: { type: "value", max: mode === "share" ? 100 : undefined }, series: [{ type: "bar", data: states.map(valueOf) }] };
  const heatmap = useMemo(() => {
    const matrix = temporalMatrix(filteredFacts, heatmapGroup.key, heatmapGroup.render);
    const groupIndex = new Map(matrix.groups.map((item, index) => [item.key, index])); const periodIndex = new Map(matrix.periods.map((item, index) => [item, index]));
    const data = matrix.cells.map((cell) => ({ name: cell.group, value: [periodIndex.get(cell.period) ?? 0, groupIndex.get(cell.group) ?? 0, cell.quantity] }));
    const option: EChartsCoreOption = { tooltip: { formatter: (params: unknown) => { const item = params as { name: string; value: number[] }; return `<strong>${matrix.groups[item.value[1]]?.label ?? item.name}</strong><br>${matrix.periods[item.value[0]]}<br>${number.format(item.value[2])} respondidos`; } }, grid: { left: 165, right: 25, top: 15, bottom: 78 }, xAxis: { type: "category", data: matrix.periods, splitArea: { show: true }, axisLabel: { rotate: 45 } }, yAxis: { type: "category", data: matrix.groups.map((item) => item.label), splitArea: { show: true } }, visualMap: { min: 0, max: Math.max(...data.map((item) => Number(item.value[2])), 1), calculable: true, orient: "horizontal", left: "center", bottom: 0, inRange: { color: ["#edf7fc", "#20aaee", "#003770"] } }, series: [{ type: "heatmap", data, emphasis: { itemStyle: { shadowBlur: 8, shadowColor: "rgba(0,55,112,.45)" } } }] };
    return { option, periods: matrix.periods };
  }, [filteredFacts, heatmapGroup]);
  const selectForm = (name: string) => { const form = forms.find((item) => item.label === name); if (form) drillTo({ formId: [form.key] }); };
  return <section className="analytics-section" id="secao-2" aria-labelledby="analytics-title">
    <div className="panel-heading"><div><p className="eyebrow">LEITURA COORDENADA</p><h2 id="analytics-title">Indicadores e proporções</h2></div><div className="segmented" aria-label="Unidade dos gráficos"><button className={mode === "quantity" ? "active" : ""} onClick={() => setMode("quantity")}>Quantidade</button><button className={mode === "share" ? "active" : ""} onClick={() => setMode("share")}>Participação</button></div></div>
    <div className="kpi-grid"><article><span>Respondidos</span><strong>{number.format(total)}</strong></article><article><span>Anos</span><strong>{distinct("year")}</strong></article><article><span>Formulários</span><strong>{distinct("formId")}</strong></article><article><span>Conselhos</span><strong>{distinct("council")}</strong></article><article><span>Unidades</span><strong>{distinct("unitSummary")}</strong></article><article><span>Responsáveis</span><strong>{distinct("responsibleName")}</strong></article></div>
    <div className="chart-grid"><article className="chart-card chart-wide"><h3>Evolução mensal</h3><EChart option={timeline} ariaLabel="Série mensal de formulários respondidos" /></article><article className="chart-card heatmap-card chart-wide"><div className="chart-card-heading"><div><h3>Heatmap temporal</h3><span>Intensidade mensal conforme o agrupamento escolhido</span></div><label><span>Agrupar por</span><select value={heatmapGroup.key} onChange={(event) => setHeatmapGroup(heatmapGroups.find((item) => item.key === event.target.value) ?? heatmapGroups[0])}>{heatmapGroups.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label></div><EChart option={heatmap.option} ariaLabel={`Heatmap temporal agrupado por ${heatmapGroup.label}`} onSelect={(name, value) => { const coordinates = value as number[]; const period = heatmap.periods[coordinates[0]]; if (!period) return; const [year, month] = period.split("-"); drillTo({ [heatmapGroup.key]: [name], year: [year], month: [String(Number(month))] }); }} /></article><article className="chart-card"><h3>Top formulários</h3><EChart option={formBars} ariaLabel="Ranking dos dez principais formulários" onSelect={selectForm} /></article><article className="chart-card"><h3>Composição dos formulários</h3><EChart option={treemap} ariaLabel="Treemap da composição por formulário" onSelect={selectForm} /></article><article className="chart-card chart-wide"><h3>Distribuição territorial</h3><EChart option={stateBars} ariaLabel="Proporção de respondidos por unidade federativa" onSelect={(name) => drillTo({ state: [name] })} /></article></div>
    <details className="visual-alternative"><summary>Consultar dados dos gráficos em lista</summary><ol>{forms.slice(0, 10).map((item) => <li key={item.key}><button onClick={() => drillTo({ formId: [item.key] })}>{item.label}: {number.format(item.quantity)} ({percent.format(item.share)})</button></li>)}</ol></details>
  </section>;
}
