import type { EChartsCoreOption } from "echarts/core";
import { EChart } from "./EChart";
import type { ResponseDimensions } from "../types/responses";

const total=(rows:number[][],index:number)=>rows.reduce((sum,row)=>sum+row[index],0);
export function ResponseProfileAnalysis({facts,profiles,dimensions,denominator,formName,questionLabel}:{facts:number[][];profiles:number[][];dimensions:ResponseDimensions;denominator:number;formName?:string;questionLabel?:string}){
 const optionMap=new Map<string,{total:number;sex:Map<string,number>;age:Map<string,number>}>();
 facts.forEach(f=>{const label=dimensions.options[f[11]].label,item=optionMap.get(label)??{total:0,sex:new Map(),age:new Map()};item.total+=f[12];item.sex.set(dimensions.sexes[f[6]],(item.sex.get(dimensions.sexes[f[6]])??0)+f[12]);item.age.set(dimensions.ageBands[f[7]],(item.age.get(dimensions.ageBands[f[7]])??0)+f[12]);optionMap.set(label,item)});
 const options=[...optionMap].sort((a,b)=>b[1].total-a[1].total).slice(0,15),sexDenominators=new Map<string,number>(),ageTotals=new Map<string,number>(),councilTotals=new Map<string,number>();
 profiles.forEach(f=>{sexDenominators.set(dimensions.sexes[f[6]],(sexDenominators.get(dimensions.sexes[f[6]])??0)+f[9]);ageTotals.set(dimensions.ageBands[f[7]],(ageTotals.get(dimensions.ageBands[f[7]])??0)+f[9]);});
 facts.forEach(f=>councilTotals.set(dimensions.councils[f[3]],(councilTotals.get(dimensions.councils[f[3]])??0)+f[12]));
 const sexColors:Record<string,string>={Feminino:"#A85FA8",Masculino:"#2E72E0"};
 const bubble:EChartsCoreOption={tooltip:{formatter:(raw:unknown)=>{const p=raw as {seriesName:string;name:string;value:number[]};return `<b>${p.name}</b><br>${p.seriesName}: ${p.value[2].toLocaleString("pt-BR")} seleções<br>${p.value[0].toLocaleString("pt-BR",{maximumFractionDigits:1})}% dos formulários com esse perfil`}},legend:{top:0},grid:{left:190,right:30,top:45,bottom:45},xAxis:{type:"value",name:"% dentro do sexo",axisLabel:{formatter:"{value}%"}},yAxis:{type:"category",data:options.map(x=>x[0]).reverse()},series:dimensions.sexes.map(sex=>({name:sex,type:"scatter",itemStyle:{color:sexColors[sex]??"#5B8FA3",opacity:.82},data:options.map(([name,item])=>{const quantity=item.sex.get(sex)??0,base=sexDenominators.get(sex)??0;return {name,value:[base?quantity/base*100:0,name,quantity],symbolSize:Math.max(10,Math.min(54,Math.sqrt(quantity)/3))}})}))};
 const heatData:number[][]=[];options.forEach(([_,item],y)=>dimensions.ageBands.forEach((age,x)=>heatData.push([x,y,item.age.get(age)??0])));
 const heat:EChartsCoreOption={tooltip:{formatter:(raw:unknown)=>{const p=raw as {value:number[]};return `${options[p.value[1]]?.[0]}<br>${dimensions.ageBands[p.value[0]]}: <b>${p.value[2].toLocaleString("pt-BR")}</b>`}},grid:{left:190,right:30,top:20,bottom:75},xAxis:{type:"category",data:dimensions.ageBands,axisLabel:{rotate:30}},yAxis:{type:"category",data:options.map(x=>x[0])},visualMap:{min:0,max:Math.max(...heatData.map(x=>x[2]),1),orient:"horizontal",left:"center",bottom:5,inRange:{color:["#E8F5FC","#20AAEE","#003770"]}},series:[{type:"heatmap",data:heatData,label:{show:false}}]};
 const top=options[0],second=options[1],topAge=[...ageTotals].sort((a,b)=>b[1]-a[1])[0],topCouncil=[...councilTotals].sort((a,b)=>b[1]-a[1])[0],profileTotal=total(profiles,9),coverage=denominator?profileTotal/denominator*100:0;
 return <><section className="insight-panel" aria-labelledby="insight-title"><p className="eyebrow">LEITURA DO RECORTE</p><h2 id="insight-title">Síntese automática</h2><div className="insight-grid"><p>{formName?<>No formulário <strong>{formName}</strong>, </>:<>No contexto atual, </>}foram identificados <strong>{denominator.toLocaleString("pt-BR")}</strong> formulários respondidos e <strong>{profileTotal.toLocaleString("pt-BR")}</strong> com perfil, cobertura de <strong>{coverage.toLocaleString("pt-BR",{maximumFractionDigits:1})}%</strong>.</p>{questionLabel&&top&&<p>Na questão <strong>{questionLabel}</strong>, a opção líder é <strong>{top[0]}</strong>, com {top[1].total.toLocaleString("pt-BR")} seleções{second?`, ${Math.max(0,top[1].total-second[1].total).toLocaleString("pt-BR")} acima da segunda opção`:""}.</p>}{topAge&&<p>A faixa etária mais representada é <strong>{topAge[0]}</strong>, com {topAge[1].toLocaleString("pt-BR")} formulários com perfil.</p>}{topCouncil&&<p>O maior volume de seleções está no conselho <strong>{topCouncil[0]}</strong>, com {topCouncil[1].toLocaleString("pt-BR")} registros no recorte.</p>}</div><small>Leitura descritiva e auditável. Não atribui desempenho positivo ou negativo sem meta formal.</small></section>{questionLabel&&<section className="analytics-section"><header className="panel-heading"><div><p className="eyebrow">PERFIL DAS OPÇÕES</p><h2>Comparação por sexo e idade</h2></div><span className="panel-note">Posição representa taxa dentro do sexo; tamanho representa quantidade.</span></header><div className="chart-grid"><article className="chart-card chart-wide"><h3>Bolhas pareadas por sexo</h3><EChart ariaLabel="Comparação das opções por sexo" option={bubble}/></article><article className="chart-card chart-wide heatmap-card"><h3>Heatmap de opções por faixa etária</h3><EChart ariaLabel="Opções por faixa etária" option={heat}/></article></div></section>}</>
}
